name: Javac-LS CI

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ["17"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build & Verify using Maven
      env:
        MAVEN_OPTS: -Djdk.xml.maxGeneralEntitySizeLimit=0 -Djdk.xml.totalEntitySizeLimit=0 -Djdk.xml.entityExpansionLimit=0
      run: mvn clean verify -U -fae -e -B
